# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/876/bin/cmake

# The command to remove a file.
RM = /snap/cmake/876/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/qaqi/Desktop/Development Techniques/GameOfLife/GameofLife"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/qaqi/Desktop/Development Techniques/GameOfLife/GameofLife"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/876/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/snap/cmake/876/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/876/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/876/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/876/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/snap/cmake/876/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/876/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/snap/cmake/876/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/qaqi/Desktop/Development Techniques/GameOfLife/GameofLife/CMakeFiles" "/home/qaqi/Desktop/Development Techniques/GameOfLife/GameofLife//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/qaqi/Desktop/Development Techniques/GameOfLife/GameofLife/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameofLife

# Build rule for target.
GameofLife: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GameofLife
.PHONY : GameofLife

# fast build rule for target.
GameofLife/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/build
.PHONY : GameofLife/fast

#=============================================================================
# Target rules for targets named console

# Build rule for target.
console: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 console
.PHONY : console

# fast build rule for target.
console/fast:
	$(MAKE) $(MAKESILENT) -f console/CMakeFiles/console.dir/build.make console/CMakeFiles/console.dir/build
.PHONY : console/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f game/CMakeFiles/game.dir/build.make game/CMakeFiles/game.dir/build
.PHONY : game/fast

console/ansi_console.o: console/ansi_console.c.o
.PHONY : console/ansi_console.o

# target to build an object file
console/ansi_console.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/console/ansi_console.c.o
.PHONY : console/ansi_console.c.o

console/ansi_console.i: console/ansi_console.c.i
.PHONY : console/ansi_console.i

# target to preprocess a source file
console/ansi_console.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/console/ansi_console.c.i
.PHONY : console/ansi_console.c.i

console/ansi_console.s: console/ansi_console.c.s
.PHONY : console/ansi_console.s

# target to generate assembly for a file
console/ansi_console.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/console/ansi_console.c.s
.PHONY : console/ansi_console.c.s

game/life.o: game/life.c.o
.PHONY : game/life.o

# target to build an object file
game/life.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/game/life.c.o
.PHONY : game/life.c.o

game/life.i: game/life.c.i
.PHONY : game/life.i

# target to preprocess a source file
game/life.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/game/life.c.i
.PHONY : game/life.c.i

game/life.s: game/life.c.s
.PHONY : game/life.s

# target to generate assembly for a file
game/life.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/game/life.c.s
.PHONY : game/life.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GameofLife.dir/build.make CMakeFiles/GameofLife.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GameofLife"
	@echo "... console"
	@echo "... game"
	@echo "... console/ansi_console.o"
	@echo "... console/ansi_console.i"
	@echo "... console/ansi_console.s"
	@echo "... game/life.o"
	@echo "... game/life.i"
	@echo "... game/life.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

